### ISSUE TITLE
Gator Grader git pull

### ISSUE THREAD

**Issue by mahoneyrAC** [Allegheny-Computer-Science-111-F2017/cs111-F2017-lab1-starter#1]
In the problems section it would be useful if the instruction explained how to get the new code for gator grader. Wouldn't it be easy enough to type `git pull ` in the gator grader directory?

**Comment by gkapfham** [comment]
Hello @mahoneyrAC --- thanks for raising this issue. I agree that this instruction should be in the `README.md` file and I have now included it. As such, I am going to close this issue. Please comment further if you think that I have not resolved the issue correctly!
